services:
  app:
    build: .
    image: eventmanager:v0.0.1
    container_name: eventmanager
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: eventmanager_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass supersecret_redis_pass