spring:
  application:
    name: ticket-hunting
    security:
      otp:
        validity-minutes: 5
      recaptcha:
        secret-key: ${RECAPCHA_SECRET_KEY}
        verify-url: https://www.google.com/recaptcha/api/siteverify
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      # CHANGE TO 'validate': Hibernate JUST ONLY CHECK Code Entity ARE MATCHING WITH THE REAL DB OR NOT.
      # IF Code HAS COLUMN DB NOT, IT IMEDIATELY NOTICE WHEN RUN app AND DON'T CREATE .
      ddl-auto: validate
    show-sql: true # Bật lên để thấy câu lệnh SQL nó chạy ngầm