CREATE TABLE bookings
(
    id              UUID           NOT NULL,
    user_id         UUID,
    event_id        UUID,
    total_amount    DECIMAL(12, 2) NOT NULL,
    ticket_quantity INTEGER        NOT NULL,
    status          VARCHAR(20),
    expires_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE events
(
    id             UUID         NOT NULL,
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    venue_id       INTEGER,
    organizer_id   UUID,
    event_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    open_sale_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         VARCHAR(20),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id            UUID           NOT NULL,
    booking_id    UUID,
    event_id      UUID,
    ticket_tier   VARCHAR(255)   NOT NULL,
    price         DECIMAL(12, 2) NOT NULL,
    seat_number   VARCHAR(255),
    attendee_name VARCHAR(255),
    qr_code       VARCHAR(255)   NOT NULL,
    status        VARCHAR(20),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE user_identities
(
    id            UUID         NOT NULL,
    user_id       UUID         NOT NULL,
    provider      VARCHAR(255) NOT NULL,
    provider_id   VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    is_verified   BOOLEAN      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_identities PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              UUID        NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(50) NOT NULL,
    identity_number VARCHAR(50) NOT NULL,
    identity_type   VARCHAR(20),
    phone_number    VARCHAR(255),
    role            VARCHAR(20),
    status          VARCHAR(20),
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE venues
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                             NOT NULL,
    city             TEXT                                     NOT NULL,
    district         TEXT                                     NOT NULL,
    ward             TEXT                                     NOT NULL,
    street           TEXT                                     NOT NULL,
    capacity         INTEGER                                  NOT NULL,
    layout_image_url TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_venues PRIMARY KEY (id)
);

ALTER TABLE tickets
    ADD CONSTRAINT uc_tickets_qrcode UNIQUE (qr_code);

ALTER TABLE user_identities
    ADD CONSTRAINT uc_user_identities_providerid UNIQUE (provider_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_identitynumber UNIQUE (identity_number);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_EVENTID FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venues (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE user_identities
    ADD CONSTRAINT FK_USER_IDENTITIES_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);